// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORM_LINQ.Models.DB;

#nullable disable

namespace ORM_LINQ.Migrations
{
    [DbContext(typeof(ORMContext))]
    [Migration("20221109082353_Initiation")]
    partial class Initiation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ORM_LINQ.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CityPostalcode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Housenumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AddressId");

                    b.HasIndex("CityPostalcode");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("ORM_LINQ.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BillId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ArticleId");

                    b.HasIndex("BillId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("ORM_LINQ.Models.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Prize")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("BillId");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("ORM_LINQ.Models.City", b =>
                {
                    b.Property<string>("Postalcode")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Postalcode");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("ORM_LINQ.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int?>("BillId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsMarried")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("CustomerId");

                    b.HasIndex("AddressId");

                    b.HasIndex("BillId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ORM_LINQ.Models.Evaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EvaluationId");

                    b.HasIndex("ArticleId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("ORM_LINQ.Models.Address", b =>
                {
                    b.HasOne("ORM_LINQ.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityPostalcode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("ORM_LINQ.Models.Article", b =>
                {
                    b.HasOne("ORM_LINQ.Models.Bill", null)
                        .WithMany("Article")
                        .HasForeignKey("BillId");
                });

            modelBuilder.Entity("ORM_LINQ.Models.Customer", b =>
                {
                    b.HasOne("ORM_LINQ.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ORM_LINQ.Models.Bill", null)
                        .WithMany("Customer")
                        .HasForeignKey("BillId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("ORM_LINQ.Models.Evaluation", b =>
                {
                    b.HasOne("ORM_LINQ.Models.Article", "Article")
                        .WithMany("Evaluations")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("ORM_LINQ.Models.Article", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("ORM_LINQ.Models.Bill", b =>
                {
                    b.Navigation("Article");

                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
